/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "StudentModule"
 * 	found in "main.asn1"
 */

#include "Student.h"

static asn_TYPE_member_t asn_MBR_Student_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Student, id),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Student, name),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Student, major),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"major"
		},
};
static const ber_tlv_tag_t asn_DEF_Student_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Student_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 1, 0, 1 }, /* name */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 2, -1, 0 } /* major */
};
static asn_SEQUENCE_specifics_t asn_SPC_Student_specs_1 = {
	sizeof(struct Student),
	offsetof(struct Student, _asn_ctx),
	asn_MAP_Student_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Student = {
	"Student",
	"Student",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Student_tags_1,
	sizeof(asn_DEF_Student_tags_1)
		/sizeof(asn_DEF_Student_tags_1[0]), /* 1 */
	asn_DEF_Student_tags_1,	/* Same as above */
	sizeof(asn_DEF_Student_tags_1)
		/sizeof(asn_DEF_Student_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Student_1,
	3,	/* Elements count */
	&asn_SPC_Student_specs_1	/* Additional specs */
};

