/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "StudentModule"
 * 	found in "main.asn1"
 */

#ifndef	_Student_H_
#define	_Student_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Student */
typedef struct Student {
	long	 id;
	PrintableString_t	 name;
	PrintableString_t	 major;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Student_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Student;

#ifdef __cplusplus
}
#endif

#endif	/* _Student_H_ */
#include <asn_internal.h>
